#!/bin/bash
#cmake -DCMAKE_C_COMPILER='/usr/bin/gcc' -B build -S base
cmake -DCMAKE_C_COMPILER='/usr/bin/gcc'  -Dgtest_build_samples=ON -B build -S base
cd /home/jasonj/work/github/codelab/build
make
